/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mysparkjava;

import org.junit.Before;
import org.junit.After;
import org.junit.Test;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.*;
import static spark.Spark.awaitInitialization;
import static spark.Spark.stop;

import kong.unirest.*;

public class RouteRootTest {
    App app = new App();

    @Before
    public void setUp() throws Exception {
        app.newRoutes();
        awaitInitialization();
    }

    @After
    public void tearDown() throws Exception {
        stop();
    }

    @Test
    public void testRootGET() {

        String testUrl = "/";

        HttpResponse<String> response = Unirest.get("http://localhost:4567/").asString();

        assertEquals(app.rootString(), response.getBody());
        assertEquals(200, response.getStatus());
    }
}
